### ISSUE TITLE
Packet: Empty CLC causes silent failure

### ISSUE THREAD

**Issue by DGollings** [kinvolk/lokomotive-kubernetes#132]
```
  clc_snippets = [
    "${file("./snippets/enable-ntpd")}"
]
```

File exists, but is empty (oops). This causes none of the worker nodes to be created.

Example git patch output:
```
diff --git a/main.tf b/main.tf
index b31a2aa..e392b60 100644
--- a/main.tf
+++ b/main.tf
@@ -90,6 +90,7 @@ module "worker-pool-helium" {
   type         = "t1.small.x86"

   clc_snippets = [
+    "${file("./snippets/enable-ntpd")}",
(other working snippets)}"
   ]
diff --git a/snippets/enable-ntpd b/snippets/enable-ntpd
new file mode 100644
```

Shows an empty file, so I'm quite sure this is what caused it.

**Comment by mauriciovasquezbernal** [comment]
Hello @DGollings, 

Which version of lokomotive-kubernetes are you using? I tried with 0af508cef8078f8956a90695488575fc062aea35 and I'm not able to reproduce this issue.

**Comment by DGollings** [comment]
Hmm, I'm using master. I'll retest later and will let you know what happens

**Comment by mauriciovasquezbernal** [comment]
Just to be sure, master now supports Terraform 0.12, I used the following syntax without string interpolation:

```
...
  clc_snippets = [
    file("./empty"),
    file(<path to valid CLC file>),
  ]
....
```

**Comment by DGollings** [comment]
Odd, but haven't been able to reproduce. Closing for now, thanks
