### ISSUE TITLE
[Packet] Automatic node_private_cidr

### ISSUE THREAD

**Issue by DGollings** [kinvolk/lokomotive-kubernetes#159]
Maybe more of a question than issue, but is there any reason why the node_private_cidr value needs to be set manually?

This part (from the example config)

>   This is different for each project on Packet and depends on the packet facility/region.
>   Check yours from the `IPs & Networks` tab from your Packet.net account.
>   If an IP block is not allocated yet, try provisioning an instance from the console in
>   that region. Packet will allocate a public IP CIDR

Because for whatever reason (cluster was down for two weeks whilst I continued development) mine changed _without deleting the project_ and it was not fun trying to figure out why like 20% of intra-node connectivity was working (apart from why _any_ connectivity was working) :)

The potential issue is of course that its an array, but is it even possible to have multiple private ip ranges? Could [0] be a reasonable default?

Suggested change:
```
# This is different for each project on Packet (...) Packet will allocate a public IP CIDR.
  node_private_cidr = data.packet_ip_block_ranges.k8s.private_ipv4[0]
}

data "packet_ip_block_ranges" "k8s" {
  project_id = local.project_id
}
```

**Comment by invidian** [comment]
There was an attempt to make it work in #43, please see it for more context.

**Comment by DGollings** [comment]
Figured something like that, 

two alternatives could either be 
this solution but with an empty project id and a comment that you need to deploy _something_ at least once, basically the same thing but slightly more self maintaining
or at least mention in that same comment that the private cidr is not 100% static, can change in some situations and to check whenever there's weird internet connectivity issues

example:
kubectl get pods works,  (you -> controller)
kubectl logs container times out (you -> controller -> pod I believe)
and something like Linkerd which is a mesh will never boot

**Comment by rata** [comment]
Hi!

Would you like to create a PR adding that the cidr might change if you delete all servers in the region? You can add it to the comment [here](https://github.com/kinvolk/lokomotive-kubernetes/blob/master/docs/flatcar-linux/packet.md#cluster) and [here](https://github.com/kinvolk/lokomotive-kubernetes/blob/master/docs/flatcar-linux/packet.md#controller-module), maybe?

Also, note while this is not documented when you create any server, **Packet** adds a route for "10.0.0.0/8" to use the private IP on your server. Therefore, while not reliable, you can use that for `node_private_cidr` and not bother with it changing for now (as this is not documented nor stable in any way, this might create a problem in the future. Use it at your own risk). Also note that if you have servers in the same project, they will be whitelisted for the firewall rules too. So, **really** use it at your own risk.

I have some ideas on how to automate this, I need to experiment (I think something as simple as using the same here https://github.com/kinvolk/lokomotive-kubernetes/pull/43, but to make it depend on the controller, can do the trick as that way the node is created). But I don't expect to have time in the near future

**Comment by pothos** [comment]
The other servers in the project have access if you use the regions private CIDR as well, so that does not speak against using `10.0.0.0/8`. It should have been the default.

**Comment by rata** [comment]
Right, you are correct :). I guess it will only change in the case of Packet backend transfer enabled and servers in other regions.

**Comment by DGollings** [comment]
so is 10.0.0.0/8 a sane and reasonable safe default? Or still very much at your own risk?

**Comment by pothos** [comment]
It means that you trust Packet to not inject any outside traffic into your private network. You have to trust  that is works in both cases anyway, but if you narrow the CIDR down to the smallest possible CIDR it will also reduce the range of possible source addresses.

**Comment by DGollings** [comment]
I once ran an active scan of [kube-hunter](https://github.com/aquasecurity/kube-hunter) and it returned kubernetes instances and IP addresses I didn't recognize at all. 
(but to be fair couldn't confirm or deny whether I had at one point created that cluster and it was somehow still running somewhere in a 'masked' mode on my private network)

so....

I think I'll stick to a small CIDR :)

@rata I'll write some docs later

**Comment by invidian** [comment]
@DGollings can we close this issue now?
