### ISSUE TITLE
Parameterize the `source` value in bootkube.tf

### ISSUE THREAD

**Issue by surajssd** [kinvolk/lokomotive-kubernetes#35]
We have the module bootkube with source value hardcoded, can we have a variable with default value to be following (which we wish to hardcode) and then user can change if they want to.

https://github.com/kinvolk/lokomotive-kubernetes/blob/fbb7eee2cd38a81019ed292a8a5eb6ae05328957/packet/flatcar-linux/kubernetes/bootkube.tf#L1-L4

**Comment by invidian** [comment]
module source cannot be interpolated in current version of Terraform, so we have to do it this way... Also see https://github.com/hashicorp/terraform/issues/1439.

**Comment by surajssd** [comment]
Oh I see
