### ISSUE TITLE
Remove `worker_count` variable

### ISSUE THREAD

**Issue by johananl** [kinvolk/lokomotive-kubernetes#38]
https://github.com/kinvolk/lokomotive-kubernetes/blob/546e48004d76cb7d99c8211f04a170e20e918fe9/packet/flatcar-linux/kubernetes/ssh.tf#L107

We may be able to get rid of this variable and use the length of `${var.worker_nodes_hostnames}` instead. Explicitly specifying the count seems a bit redundant to me.

I don't remember if we can use `length()` inside a `count` though.

**Comment by invidian** [comment]
I'm not sure if using `var.worker_nodes_hostnames` is a good idea for size of the pool. From user perspective, who does not care about hostnames and need to have 10 servers, currently, it's:
```hcl
count = 10
```

and later it will be:
```hcl
worker_nodes_hostnames = [
  "foo-0",
  "foo-1",
  "foo-2",
  "foo-3",
  "foo-4",
  "foo-5",
  "foo-6",
  "foo-7",
  "foo-8",
  "foo-9",
]
```

Or users will have to workaround that with `null_resource` via triggers:
```hcl
resource "null_resouce" "hostnames" {
  count = 10
  triggers = {
    hostname = "foo-${count.index}"
  }
}

worker_nodes_hostnames = null_resource.hostnames.*.triggers.hostname
```

I would actually suggest doing it other way around and let user specify the **pattern** for the hostnames, which we then use with combination of count.

**Comment by kosyfrances** [comment]
I agree @invidian. Using `worker_nodes_hostnames` is not a good idea.
Having to use length of `worker_nodes_hostnames` as is with current setup will not work with `count` either as `count` may only use values that can be known at plan time.

**Comment by kosyfrances** [comment]
Referencing this issue - https://github.com/kinvolk/PROJECT-Lokomotive-Kubernetes/issues/354

Since we only use the `worker_count` and `worker_nodes_hostnames` variables to set up host endpoint objects, it makes sense to remove them and mandate users to install the  [calico hostendpoint controller](https://github.com/kinvolk/calico-hostendpoint-controller).
