### ISSUE TITLE
packet: support adding autoscaler tags to nodes in worker pools

### ISSUE THREAD

**Issue by iaguis** [kinvolk/lokomotive-kubernetes#49]
The packet cluster autoscaler identifies nodes to scale with tags in packet.

I'd like to have an option to add those tags when creating worker pools in Lokomotive.

**Comment by surajssd** [comment]
What are tags? How is it different from labels?

**Comment by iaguis** [comment]
Tags are a Packet concept.

**Comment by surajssd** [comment]
Oh I see :+1:

**Comment by mpolednik** [comment]
This can be closed since #170 is in - it is generic enough to pass any tags incl. those requires by autoscaler.

**Comment by invidian** [comment]
Thanks for noticing @mpolednik, I will close it then.
