### ISSUE TITLE
Maximal Ignition config length almost reached

### ISSUE THREAD

**Issue by pothos** [kinvolk/lokomotive-kubernetes#52]
There are not may lines left to be added until provisioning will fail because the 16 kB limit is hit.

Files could either be copied at a later stage or the size brought down through compression.

**Comment by invidian** [comment]
It seems that we are trying to do too much over ignition.

**Comment by dongsupark** [comment]
FYI, as a workaround, you can replace the long part with a remote config file.
See https://coreos.com/ignition/docs/latest/examples.html#replace-the-config-with-a-remote-config.

**Comment by pothos** [comment]
It seems to be a common issue and wrapping it in gzip+base64 should help:

https://github.com/hashicorp/terraform/issues/3407

Edit:

The best way would be to compress the whole config and use `coreos.config.data.encoding=gzip+base64` as kernel parameter if it cannot detect the encoding automatically. But if that doesn't work, single file entries can compressed by preprocessing `content:` and adding `encoding: "gzip+base64"`.

Edit2: Ignition supports gzip of the whole file only for [vmware](https://github.com/flatcar-linux/ignition/blob/a572e98b1dd816c9d29b8e1db8ead9198dd24903/internal/providers/vmware/vmware.go) and the requirement of passing a kernel parameter is difficult for AWS anyway. So on the long run we could either store the config on S3 (and care for security) or teach compression detection to ingition.

**Comment by invidian** [comment]
@pothos what's the status of it?

**Comment by pothos** [comment]
Addressed in https://github.com/kinvolk/lokomotive-kubernetes/pull/64
