### ISSUE TITLE
Difference between Lokomotive and typhoon

### ISSUE THREAD

**Issue by NicolaiSchmid** [kinvolk/lokomotive-kubernetes#97]
How does this project differentiate from [Poseidon/typhoon](https://github.com/poseidon/typhoon)?

Is it just a fork? Do you plan on building extra features into it?
Or what’s the goal of this project?
Maybe I’m overlooking something. 
Thanks for your reply!

**Comment by pothos** [comment]
Differences I can quickly highlight are [Packet](https://www.packet.com/) support, using Bootkube for a self-hosted control plane, an experimental libvirt/KVM platform, and focus on integration with Flatcar Container Linux. For a more general description and roadmap, see [here](https://kinvolk.io/blog/2019/05/driving-kubernetes-forward-with-lokomotive/).
